# Generated by Django 4.1.1 on 2022-10-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
    ]
